#@ load("@ytt:data", "data")
---
apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
  name: greenplumdata
spec:
  image: registry.pivotal.io/tanzu-gemfire-for-kubernetes/gemfire-k8s:1.0.3
  security:
    tls: { }
  serialization:
    pdx:
      readSerialized: true
  locators:
    libraries:
      - name: gemfire-greenplum-connector
        container:
          image: oawofolu/gemfire-greenplum-connector:latest
          path: "/opt/*.jar"
          imagePullSecretRef:
            name: image-pull-secret-2
    overrides:
      jvmOptions:
        - "-Djava.net.preferIPv4Stack=true"
  servers:
    libraries:
      - name: gemfire-greenplum-connector
        container:
          image: oawofolu/gemfire-greenplum-connector:latest
          path: "/opt/*.jar"
          imagePullSecretRef:
            name: image-pull-secret-3
    overrides:
      jvmOptions:
        - "-Djava.net.preferIPv4Stack=true"
      gemFireProperties:
        - name: "start-dev-rest-api"
          value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: greenplumdata-dev-api
spec:
  selector:
    gemfire.vmware.com/app: greenplumdata-server
  ports:
    - name: rest-api
      port: 7070
      targetPort: 7070

---
apiVersion: v1
kind: Service
metadata:
  name: greenplumdata-mgmt-api
spec:
  selector:
    gemfire.vmware.com/app: greenplumdata-locator
  ports:
    - name: management
      port: 7070
      targetPort: 7070

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: greenplumdata-dev-api-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: greenplumdata-dev-api
          port: 7070
      loadBalancerPolicy:
        strategy: Cookie
  virtualhost:
    fqdn: #@ 'greenplumdata-server.' + data.values.fqdn_domain

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: greenplumdata-mgmt-api-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: greenplumdata-mgmt-api
          port: 7070
      loadBalancerPolicy:
        strategy: Cookie
  virtualhost:
    fqdn: #@ 'greenplumdata-locator.' + data.values.fqdn_domain


