#@ load("@ytt:data", "data")
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmqanomaly
spec:
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_peer_discovery_k8s
  service:
    type: LoadBalancer

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: rmqanomaly-mgmt-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: rmqanomaly
          port: 15672
  virtualhost:
    fqdn: #@ 'rmqanomaly.' + data.values.fqdn_domain
