---
apiVersion: v1
kind: Secret
metadata:
  name: rmq-demo-secret
type: Opaque
stringData:
  username: vmware
  password: vmware
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rmq-demo-user
spec:
  rabbitmqClusterReference:
    name:  rmqanomaly
  importCredentialsSecret:
    name: rmq-demo-secret
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rmq-demo-user-perm
spec:
  vhost: "/"
  userReference:
    name: rmq-demo-user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rmqanomaly
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: mds-fraud-transactions
spec:
  name: mds-fraud-transactions
  autoDelete: false
  durable: true
  type: quorum
  rabbitmqClusterReference:
    name: rmqanomaly
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: mds-fraud-transactions-exchange
spec:
  name: mds-fraud-transactions-exchange
  type: topic
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rmqanomaly
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: mds-fraud-transactions-exchange-global
spec:
  name: mds-fraud-transactions-exchange-global
  type: topic
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rmqanomaly
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: mds-fraud-transactions-alt-exchange
spec:
  name: mds-fraud-transactions-alt-exchange
  type: fanout
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rmqanomaly
---
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: mds-fraud-alt-exchange-policy
spec:
  name: mds-fraud-alt-exchange-policy
  pattern: "^mds-fraud-transactions."
  applyTo: "exchanges"
  definition:
    alternate-exchange: mds-fraud-transactions-alt-exchange
  rabbitmqClusterReference:
    name: rmqanomaly