#@ load("@ytt:data", "data")
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: random-forest-train-workflow
spec:
  templates:
    - name: train
      steps:
        - - name: publish-model
            template: run-training
            arguments:
              parameters:
                - name: entrypoint
                  value: "./app/publish_randomforest_model.py"

    - name: run-training
      inputs:
        parameters:
          - name: entrypoint
          - name: model_name
            value: 'model'
      container:
        image: oawofolu/demo-ml-base
        command: [ python ]
        args:
          - "{{inputs.parameters.entrypoint}}"