#@data/values
---
model_stage: Staging
git_repo: https://github.com/agapebondservant/data-e2e-demo-app.git
experiment_name: anomaly_detection
environment_name: gitops
script_shared_path: /liquibase/changelog
mlpipeline_git_repo: https://github.com/agapebondservant/data-e2e-demo-app.git
onnxpackaging_git_repo: https://github.com/agapebondservant/onnxruntime.git
pyfunction_vendored_dependencies_uri: https://tolatest-temp-resources.s3.us-east-2.amazonaws.com/vendor2.tar.gz
mlflow_s3_uri: http://minio-ml.tanzudatatap.com
mlflow_tracking_uri: http://mlflow.tanzudatatap.com
datahub_rest_uri: datahub-gms-datahub.tanzudatatap.com
shared_rabbit_secret: rmqanomaly-default-user
shared_rabbit_host: a1fb9dcb4d9f948cd87a3ef745004bf1-1827317288.us-east-1.elb.amazonaws.com
shared_argo_artifact_server: minio-argo.tanzudatatap.com
shared_argo_artifact_server_bucket: demo
shared_argo_events_amqp_exchange: mds-fraud-transactions-exchange-global
shared_argo_events_amqp_routing_key: downstream.randomforest.madlib
jdk_image: openjdk:11.0-jdk
onnx_java_target_image: oawofolu/onnx-java
onnx_gemfire_cluster_template: deploy/templates/demo-data/gemfire-cluster.yaml
onnx_gemfire_dockerfile_template: deploy/templates/dockerfiles/onnx-gemfire
docker_buildkit_secret_name: docker-config
gemfire_repo_secret_name: gemfire-repo
gemfire_repo_secret_name_username_key: gemfire_repo_username
gemfire_repo_secret_name_password_key: gemfire_repo_password

training_shared_path: /usr/local/greenplum-db/bin/plcontainer_clients
training_db_script: demo-ml/resources/sql/random_forest_madlib_training.sql
training_hyperparameters_db_script: demo-ml/resources/sql/hyperparameters.sql
training_code_shell_script: demo-ml/resources/shell/deploy_training_code.sh
training_db_shell_script: demo-ml/resources/shell/deploy_training_db.sh
training_user: gpadmin
training_master: ec2-44-201-91-88.compute-1.amazonaws.com
training_db_name: dev
training_external_secret_ref: greenplum-training-secret
training_external_secret_ref_key: greenplum_master_password
training_db_schema: public
training_image: kroniak/ssh-client
training_db_uri: jdbc:postgresql://44.201.91.88:5432/dev?sslmode=require&prepareThreshold=0

inference_user: postgres
inference_host: aa28023c2f2614eb188934e99167ce65-1434640867.us-east-1.elb.amazonaws.com
inference_db_name: postgres
inference_shared_path: /usr/local
inference_db_script: demo-ml/resources/sql/random_forest_madlib_inference.sql
inference_code_shell_script: demo-ml/resources/shell/deploy_inference_code.sh
inference_db_shell_script: demo-ml/resources/shell/deploy_inference_db.sh
inference_external_secret_ref: postgres-inference-secret
inference_external_secret_ref_key: postgres_password
inference_namespace: default
inference_db_schema: public
inference_image: alpine/k8s:1.23.17
inference_db_uri: jdbc:postgresql://aa28023c2f2614eb188934e99167ce65-1434640867.us-east-1.elb.amazonaws.com:5432/postgres?prepareThreshold=0
inference_cache_gemfire_server: http://gfanomaly-server.tanzudatatap.com
