server:
  port: 8090
  maxHttpHeaderSize: 131072

spring:
  datasource:
    url: jdbc:h2:file:./opt/data/db;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

rmq:
  listeners:
    queue:
      fraud-transactions: mds-fraud-transactions
    exchange: mds-fraud-transactions-exchange

gemfire:
  region: mds-region
  url: http://gfanomaly-locator.tanzudatatap.com/geode-mgmt/v1/management/commands

fraud:
  detection:
    distance-threshold-in-kms: 10
    time-threshold-in-seconds: 600

mlmodel:
  registry: http://mlflow.tanzudatatap.com
