apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-app-pv
  namespace: vmware-explore
spec:
  storageClassName: gp2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/vmware/demo
