apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  labels:
    app: demo-app-svc
  namespace: vmware-explore
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  type: ClusterIP
  selector:
    app: demo-app
