apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: fraud-detection-appcr
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: https://github.com/agapebondservant/data-e2e-demo-app.git
        ref: origin/gitops

  template:
    - ytt:
        paths:
          - demo-ml/argo/install-argo-events-eventbus.yaml
          - demo-ml/argo/argo-rabbitmq-eventsource.yaml
          - demo-ml/argo/ml-training-pipeline.yaml
          - demo-ml/argo/argo-rabbitmq-ml-inference-trigger.yaml
          - demo-ml/argo/argo-rabbitmq-ml-onnx-inference-trigger.yaml
          - demo-ml/argo/values.yaml
          - .git/HEAD

  deploy:
    - kapp: {}