---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ui-dep
  labels:
    app: demo-ui-dep
  namespace: vmware-explore
spec:
  replicas: 1
  selector:
    matchLabels:
     app: demo-ui
  template:
    metadata:
      labels:
        app: demo-ui
    spec:
      imagePullSecrets:
        - name: image-pull-secret
      containers:
      - name: demo-ui
        image: oawofolu/demo-ui-anomaly #irisdev21/demo-ui:init
        ports:
          - containerPort: 8080