---
apiVersion: v1
kind: Service
metadata:
  name: demo-ui-svc
  labels:
    app: demo-ui-svc
  namespace: vmware-explore
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: demo-ui