apiVersion: v1
kind: Service
metadata:
  name: demo-ui-svc
  labels:
    app: demo-ui-svc
  namespace: vmware-explore
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: demo-ui
